import { Project } from "@/types/project"

export const getProjects = (t: (key: string) => string): Project[] => [
  {
    title: t('items.ticket_world.title'),
    description: t('items.ticket_world.description'),
    image: "/images/projects/ticket-world/TicketWorld_1.webp",
    tags: ["Python", "Django", "PostgreSQL", "JavaScript", "HTML/CSS"],
    liveUrl: "https://ticket-world.onrender.com",
    githubUrl: "https://github.com/Arcay322/Ticket_World",
    featured: true,
    isNew: false,
    date: "2024-09-15",
    // Multimedia gallery - cambia el número 3 por cuantas imágenes tengas
    media: Array.from({ length: 3 }, (_, i) => ({
      type: "image" as const,
      src: `/images/projects/ticket-world/TicketWorld_${i + 1}.webp`,
      alt: `Ticket World - Captura ${i + 1}`,
    })),
    relatedProjects: ["sumaq-uywa"],
    longDescription: t('items.ticket_world.long_description'),
    features: [
      t('items.ticket_world.features.auth'),
      t('items.ticket_world.features.admin'),
      t('items.ticket_world.features.metrics'),
      t('items.ticket_world.features.maps'),
      t('items.ticket_world.features.payments'),
      t('items.ticket_world.features.events'),
      t('items.ticket_world.features.cart'),
      t('items.ticket_world.features.responsive'),
    ],
    challenges: [
      t('items.ticket_world.challenges.roles'),
      t('items.ticket_world.challenges.maps'),
      t('items.ticket_world.challenges.queries'),
      t('items.ticket_world.challenges.architecture'),
    ],
  },
  {
    title: t('items.sumaq_uywa.title'),
    description: t('items.sumaq_uywa.description'),
    image: "/images/projects/sumaq-uywa/SumaqUywa_1.webp",
    tags: ["React", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    liveUrl: "https://sumaq-uywa-fontend.onrender.com",
    githubUrl: "https://github.com/Arcay322/Granja_cuyes",
    featured: true,
    isNew: true,
    date: "2024-10-01",
    // Multimedia gallery - cambia el número 9 por cuantas imágenes tengas
    media: Array.from({ length: 9 }, (_, i) => ({
      type: "image" as const,
      src: `/images/projects/sumaq-uywa/SumaqUywa_${i + 1}.webp`,
      alt: `Sumaq Uywa - Captura ${i + 1}`,
    })),
    relatedProjects: ["ticket-world"],
    longDescription: t('items.sumaq_uywa.long_description'),
    features: [
      t('items.sumaq_uywa.features.dashboard'),
      t('items.sumaq_uywa.features.reproduction'),
      t('items.sumaq_uywa.features.health'),
      t('items.sumaq_uywa.features.feeding'),
      t('items.sumaq_uywa.features.sales'),
      t('items.sumaq_uywa.features.expenses'),
      t('items.sumaq_uywa.features.notifications'),
      t('items.sumaq_uywa.features.reports'),
      t('items.sumaq_uywa.features.responsive'),
    ],
    challenges: [
      t('items.sumaq_uywa.challenges.database'),
      t('items.sumaq_uywa.challenges.notifications'),
      t('items.sumaq_uywa.challenges.performance'),
      t('items.sumaq_uywa.challenges.charts'),
    ],
  },
  {
    title: t('items.ventify.title'),
    description: t('items.ventify.description'),
    image: "/images/projects/ventify/Ventify_1.webp",
    tags: ["Next.js", "TypeScript", "Firebase", "Tailwind CSS", "React"],
    liveUrl: "https://ventify-one.vercel.app/",
    githubUrl: "https://github.com/Arcay322/Ventify.git",
    featured: true,
    isNew: true,
    inProduction: true,
    date: "2025-01-01",
    // Multimedia gallery - cambia el número 12 por cuantas imágenes tengas
    media: Array.from({ length: 12 }, (_, i) => ({
      type: "image" as const,
      src: `/images/projects/ventify/Ventify_${i + 1}.webp`,
      alt: `Ventify - Captura ${i + 1}`,
    })),
    relatedProjects: ["ticket-world", "sumaq-uywa"],
    longDescription: t('items.ventify.long_description'),
    features: [
      t('items.ventify.features.multibranch'),
      t('items.ventify.features.realtime'),
      t('items.ventify.features.reservations'),
      t('items.ventify.features.custom_orders'),
      t('items.ventify.features.cash_control'),
      t('items.ventify.features.permissions'),
      t('items.ventify.features.reports'),
      t('items.ventify.features.payments'),
      t('items.ventify.features.warehouses'),
      t('items.ventify.features.alerts'),
      t('items.ventify.features.responsive'),
    ],
    challenges: [
      t('items.ventify.challenges.realtime_sync'),
      t('items.ventify.challenges.complex_permissions'),
      t('items.ventify.challenges.concurrent_access'),
      t('items.ventify.challenges.scalability'),
      t('items.ventify.challenges.offline_support'),
      t('items.ventify.challenges.performance'),
    ],
  },
];


